### ISSUE TITLE
Image Restoration and Color Enhancement?

### ISSUE THREAD

**Issue by dingdingbin** [rfuruta/pixelRL#1]
Can you publish  the code for the Image Restoration and Color Enhancement sections?

**Comment by rfuruta** [comment]
Thank you for your interest in our paper! We are now focusing on publishing this work as a journal paper. So, the codes for the two applications might be released after the journal version is accepted.

**Comment by machanic** [comment]
@rfuruta Two years have been passed, can you share the codes of the Image Restoration and Color Enhancement now?

**Comment by rfuruta** [comment]
I have updated README.md. You can get the codes for the two applications from the link on the document.
