### ISSUE TITLE
Can pixelRL be combined with GAN?

### ISSUE THREAD

**Issue by FightingSrain** [rfuruta/pixelRL#8]

**Comment by rfuruta** [comment]
Currently, pixelRL cannot be directly combined with GAN because the gradient information from a discriminator cannot be backprogated for the agents.

**Comment by FightingSrain** [comment]
Thank you for your answer!!
I also have a question, if I use pixelRL as a generator and add a discriminator to generate reward,  using WGAN reward instead of L2 reward and updating WGAN loss when updating A3C loss, is it feasible? I want to know what you think.

**Comment by FightingSrain** [comment]
> 目前，pixelRL无法直接与GAN结合使用，因为无法对识别符反向传播来自鉴别器的梯度信息。
Thank you for your answer!!
I also have a question, if I use pixelRL as a generator and add a discriminator to generate reward, using WGAN reward instead of L2 reward and updating WGAN loss when updating A3C loss, is it feasible? I want to know what you think.

**Comment by FightingSrain** [comment]
> Currently, pixelRL cannot be directly combined with GAN because the gradient information from a discriminator cannot be backprogated for the agents.

Thank you for your answer!!
I also have a question, if I use pixelRL as a generator and add a discriminator to generate reward, using WGAN reward instead of L2 reward and updating WGAN loss when updating A3C loss, is it feasible? I want to know what you think

**Comment by rfuruta** [comment]
In order to train pixelRL as a generator, you need pixel-wise rewards. If the discriminator can generate pixel-wise rewards, your idea will be feasible.
